# Generated by Django 6.0.6 on 2026-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_baseuser_email_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
